Razom/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataModel;
using Razom.Models;

namespace Razom.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Parse()
        {
            ServiceReference1.Service1Client proxy = new ServiceReference1.Service1Client();
            proxy.runParce();
            proxy.Close();
            return RedirectToAction("Index","Home");
        }

        [Authorize]
        public ActionResult TestConnection()
        {
            ServiceReference1.Service1Client proxy = new ServiceReference1.Service1Client();
            ViewBag.Message = proxy.getResponse();
            proxy.Close();
            return View();
        }

        [ChildActionOnly]
        public ActionResult PanelButton()
        {
            if (HttpContext.Request.Cookies["role"] != null && User.Identity.IsAuthenticated)
            {
                string role = HttpContext.Request.Cookies["role"].Value;
                if (role == "admin")
                {
                    return PartialView();
                }
            }
            return null;
        }
    }
}

Razom/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Razom.Models;
using System.Web.Security;
using DataModel;
using System.IO;

namespace Razom.Controllers
{
    public class PlaceController : Controller
    {
        //
        // GET: /Place/
        [Authorize]
        public ActionResult Index(int id = 1)
        {
            List<ShortPlace> result = new List<ShortPlace>();
            using (var con = new RazomContext())
            {
                HttpCookie cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
                FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                string username = ticket.Name;
                int userID = con.Users.SingleOrDefault(u => u.Login == username).UserID;
                result = (from pl in con.Places
                         join fpl in con.FuturePlace on pl.PlaceID equals fpl.PlaceID
                         //join u in con.Users on fpl.UserID equals u.UserID
                         //join p in con.PhotosPlace on pl.PlaceID equals p.PlaceID into gj
                         where fpl.UserID == userID
                         //from subres in gj.DefaultIfEmpty()
                         select new ShortPlace
                         {
                             ID = fpl.ID,
                             Name = pl.Name,
                             Rating = pl.Rating ?? 0,
                             PlaceID = pl.PlaceID,
                             //PhotoUrl = subres == null ? " ": subres.href,
                             //PhotoByte = subres.FotoID,
                             City = con.Region.FirstOrDefault(r => r.CityID == pl.CityID).Name,
                             PlaceType = con.PlaceType.FirstOrDefault(pt => pt.PlaceTypeID == pl.PlaceTypeID).Type
                         }).ToList();
                
                result.ForEach(r =>
                {
                    var photo = con.PhotosPlace.Where(pp => pp.PlaceID == r.PlaceID);
                    if (photo != null)
                    {
                        if (photo.First().FileFoto != null)
                        {
                            r.PhotoByte = photo.First().FotoID;
                        }
                        else
                            if (photo.First().href != null )
                            {
                                r.PhotoUrl = photo.First().href;
                            }    
                    }
                    
                    r.tags = (from t in con.Tag
                              join ttp in con.TagToPlace on t.TagID equals ttp.TagID
                              where ttp.PlaceID == r.PlaceID
                              select t.NameTag).ToList();
                });
            }

            int pageSize = 6;
            int pCount = 0;
            if(result.Count % pageSize == 0)
            {
                pCount = result.Count / pageSize;
            }
            else
                pCount = result.Count / pageSize + 1;

            List<ShortPlace> list = result.OrderBy(p => p.Name).Skip((id - 1) * pageSize).Take(pageSize).ToList();
            PlaceCollection pc = new PlaceCollection() { Places = list, CurrentPage = id, PagesCount = pCount };
            return View(pc);
        }

        [ChildActionOnly]
        public ActionResult MyPlacesButton()
        {
            if (HttpContext.Request.Cookies["role"] != null && User.Identity.IsAuthenticated)
            {
                return PartialView();
            }
            return null;
        }

        [Authorize]
        public ActionResult DeleteFromList(int id)
        {
            using (var db = new RazomContext())
            {
                FuturePlace ID = db.FuturePlace.Find(id);
                if (ID != null)
                {
                    db.FuturePlace.Remove(ID);
                    db.SaveChanges();
                    ViewBag.Message = "Місце успішно видалено зі списку!"; 
                    return View();
                }
            }
            ViewBag.Message = "Щось пройшло не так...";
            return View();
        }

        public ActionResult DisplayPicture(int id = -1)
        {
            if (id != -1)
            {
                using (var db = new RazomContext())
                {
                    byte[] image = db.PhotosPlace.Find(id).FileFoto;
                    if (image == null)
                    {
                        return null;
                    }
                    else
                        return File(image, "image/jpg");
                }
            }
            return null;
        }

        public ActionResult Show(int id = -1, int page = 1)
        {
            if (id != -1)
            {
                FullPlace place = new FullPlace();
                using (var db = new RazomContext())
                {
                    Places p = db.Places.SingleOrDefault(i => i.PlaceID == id);
                    place.City = db.Region.Find(p.CityID).Name;
                    place.Name = p.Name;
                    place.PlaceID = p.PlaceID;
                    place.PlaceType = db.PlaceType.Find(p.PlaceTypeID) == null ? string.Empty : db.PlaceType.Find(p.PlaceTypeID).Type;
                    place.Rating = p.Rating ?? 0;
                    place.Address = p.Address;
                    place.tags = (from pl in db.Places
                                  join ttp in db.TagToPlace on pl.PlaceID equals ttp.PlaceID
                                  join t in db.Tag on ttp.TagID equals t.TagID
                                  where pl.PlaceID == id
                                  select t.NameTag).ToList();
                    place.PhotoUrls = (from  img in db.PhotosPlace 
                                           where img.href != null && img.PlaceID == id
                                           select img.href).ToList();
                    place.PhotoBytes = (from img in db.PhotosPlace
                                        where img.FileFoto != null && img.PlaceID == id
                                        select img.FotoID).ToList();
                    place.Coordinates = p.Coordinates;
                    HttpCookie cookie = Request.Cookies[FormsAuthentication.FormsCookieName];
                    if (cookie != null)
                    {
                        FormsAuthenticationTicket ticket = FormsAuthentication.Decrypt(cookie.Value);
                        string username = ticket.Name;
                        Users user = db.Users.SingleOrDefault(u => u.Login == username);
                        place.IsEditable = user.IsAdmin ?? false;
                        place.IsAuthorized = true;
                        place.IsInFavorite = db.FuturePlace.Where(fp => fp.PlaceID == id && fp.UserID == user.UserID).Count() == 0 ? false : true;
                    }
                    else
                    {
                        place.IsEditable = false;
                        place.IsAuthorized = false;
                    }

                    place.Comment = db.Comments.Where(c => c.PlaceID == id).ToList();
                    place.Comment.Reverse();
                    int pageSize = 3;
                    int pCount = 0;
                    if (place.Comment.Count() % pageSize == 0)
                    {
                        pCount = place.Comment.Count() / pageSize;
                    }
                    else
                        pCount = place.Comment.Count() / pageSize + 1;
                    place.Comment = place.Comment.Skip((page-1)*pageSize).Take(pageSize).ToList();
                    place.CurrentPage = page;
                    place.PagesCount = pCount;
                }
                return View(place);
            }
            return View();
        }

        private List<ShortPlace> getSearchList(string token)
        {
            PlaceSearchEngine.PlaceSearchEngine engine = new PlaceSearchEngine.PlaceSearchEngine();
            List<int> ids = engine.searchPlaces(token);
            List<ShortPlace> result = new List<ShortPlace>();
            using (var db = new RazomContext())
            {
                ShortPlace sp;
                foreach (int item in ids)
                {
                    Places p = db.Places.Find(item);
                    if (p == null)
                    {
                        continue;
                    }
                    List<string> Tags = (from t in db.Tag
                                         join ttp in db.TagToPlace on t.TagID equals ttp.TagID
                                         where ttp.PlaceID == item
                                         select t.NameTag).ToList();
                    var photo = db.PhotosPlace.Where(ph => ph.FileFoto != null && ph.PlaceID == p.PlaceID).ToList();
                    var photoUrl = db.PhotosPlace.Where(ph => ph.href != null && ph.PlaceID == p.PlaceID).ToList();
                    sp = new ShortPlace
                    {
                        Name = p.Name,
                        City = db.Region.Find(p.CityID).Name,
                        PlaceID = p.PlaceID,
                        PhotoByte = photo.Count != 0 ? photo.First().FotoID : 0,
                        PhotoUrl = photoUrl.Count != 0 ? photoUrl.First().href : "",
                        Rating = p.Rating ?? 0,
                        PlaceType = p.PlaceType != null ? db.PlaceType.Find(p.PlaceTypeID).Type : string.Empty,
                        tags = Tags
                    };
                    result.Add(sp);
                }
            }
            return result;
        }

        [HttpPost]
        public ActionResult PlaceSearch(string id = "", int page = 1)
        {
            if (id != "")
            {
                List<ShortPlace> result = getSearchList(id);

                int pageSize = 6;
                int pCount = 0;

Razom/Views/Shared/_AjaxGridPager.cshtml
@model Grid.Mvc.Ajax.GridExtensions.AjaxGridPager
@if (Model.Pages < 2)
{
    return;
}

<div class="grid-footer">
    <div class="grid-pager">
        <ul class="pagination">
            <li><a href="#" class="grid-prev-page" title="Previous Page" style="display: none"><span class="glyphicon glyphicon-step-backward"></span></a></li>
            @{if (Model.Pages > Model.PagePartitionSize+2 &&
                  Model.PagePartitionSize > 0)
              {
                  <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                  <li><a href="#" class="grid-pageSetLink prev" style="display: none;" data-pageSet='1' data-partitionSize="@Model.PagePartitionSize">...</a></li>
                  for (int i = 1; i < Model.PagePartitionSize+1; i++)
                  {
                      var currentPage = i + 1;
                       <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                  }

                   <li><a href="#" class="grid-pageSetLink next" data-pageSet='2' data-partitionSize="@Model.PagePartitionSize">...</a></li>
                   <li><a href="#" class="grid-page-link" data-page='@Model.Pages'>@Model.Pages</a></li>
              }
              else
              {
                <li class="active"><a class="grid-page-link" data-page="1">1</a></li>
                  for (int i = 1; i < Model.Pages; i++)
                  {
                      var currentPage = i + 1;
                <li><a href="#" class="grid-page-link" data-page='@currentPage'>@currentPage</a></li>
                  }
              }
            }
            <li><a href="#" title="Next Page" class="grid-next-page"><span class="glyphicon glyphicon-step-forward"></span></a></li>
        </ul>
    </div>
</div>

Razom/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

Razom/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

Razom/Views/Shared/_Layout.cshtml
<!DOCTYPE html> 
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <link href="@Url.Content("~/Content/reset.css")" media="screen" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/grid_12.css")" media="screen" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/style.css")" media="screen" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Lato:300italic" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/Gridmvc.css")" rel="stylesheet" />
        
        @if (IsSectionDefined("AdditionalCSS"))
        {
            @RenderSection("AdditionalCSS",required: false)
        }
        <script type="text/javascript" src="@Url.Content("~/Scripts/Bilbo_400.font.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/cufon-replace.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/cufon-yui.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/html5.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/jquery.easing.1.3.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/jquery-1.7.min.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/tms-0.4.1.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/bootstrap.js")"></script>
        <script type="text/javascript" src="@Url.Content("/Scripts/bootstrap.min.js")"></script>
        <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")"></script>
        <script src="@Url.Content("~/Scripts/gridmvc.min.js")"></script>
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/bootstrap.min.css")
        @Styles.Render("~/Content/bootstrap-responsive.min.css")
        @Styles.Render("~/Content/css")
        @*@Scripts.Render("~/bundles/modernizr")*@
    </head>
    <body>
        <header>
            <div>
              <div>
                  <h1><a href="/"><img src="/Images/logo.png" alt=""></a></h1>
                  <nav>
                    <ul class="menu">
                      <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                        @{Html.RenderAction("MyPlacesButton", "Place");}
                        @{Html.RenderAction("MyTripsButton", "Trip");}
                        @{Html.RenderAction("AccountButton", "Account");}
                      <li>@Html.ActionLink("Що це?","About","Home")</li>
                        @{Html.RenderAction("PanelButton", "Admin");}
                    </ul>
                  </nav>
                <div class="clear"></div>
                </div>
            </div>
        </header>
        @if (IsSectionDefined("SliderCode"))
        {
            @RenderSection("SliderCode",required: false)
        }
        <section id="content">
            @RenderSection("featured", required: false)
            @RenderBody()
        </section>
        
        
        <footer>
            <p>© 2014 Разом <br />
            Developed by brainiac, dollhead, heaventlysmile</p>
            <div class="soc-icons"><span>Follow Us:</span><a href="#"><img src="/Images/icon-1.jpg" alt=""></a><a href="#"><img src="/Images/icon-2.jpg" alt=""></a><a href="#"><img src="/Images/icon-3.jpg" alt=""></a></div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Razom/Views/Shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5shiv.js"></script>
    <![endif]-->